import React, { useEffect } from "react";
import {
  BrowserRouter as Router,
  Routes,
  Route,
  useLocation,
} from "react-router-dom";
import { useDispatch } from "react-redux";
import { setProducts } from "./redux/slices/productsSlice";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Home from "./pages/Home";
import Products from "./pages/Products";
import ProductDetail from "./pages/ProductDetail";
import Customization from "./pages/Customization";
import CreateCustomization from "./pages/CreateCustomization";
import Cart from "./pages/Cart";
import Checkout from "./pages/Checkout";
import Login from "./pages/Login";
import NotFound from "./pages/NotFound";
import TrackOrder from "./pages/TrackOrder";
import ContactUs from "./pages/ContactUs";
import Profile from "./pages/Profile";
import "./App.css";

// Scroll to top on route change
function ScrollToTop() {
  const { pathname } = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

  return null;
}

// Product data with real images
const sampleProducts = [
  // Rings (34 items)
  {
    id: 1,
    name: "Classic Diamond Ring",
    category: "Rings",
    price: 2999.99,
    description: "Stunning diamond solitaire ring with brilliant cut stone",
    material: "14K White Gold",
    weight: "3.5g",
    sku: "RNG-001",
    image: "rings-01.jpg",
    customizable: true,
  },
  {
    id: 2,
    name: "Emerald Engagement Ring",
    category: "Rings",
    price: 3499.99,
    description: "Luxurious emerald and diamond halo ring",
    material: "Platinum",
    weight: "4g",
    sku: "RNG-002",
    image: "rings-02.jpg",
    customizable: true,
  },
  {
    id: 3,
    name: "Rose Gold Band",
    category: "Rings",
    price: 799.99,
    description: "Elegant rose gold wedding band",
    material: "14K Rose Gold",
    weight: "3g",
    sku: "RNG-003",
    image: "rings-03.jpg",
    customizable: true,
  },
  {
    id: 4,
    name: "Sapphire Statement Ring",
    category: "Rings",
    price: 4299.99,
    description: "Bold sapphire ring with accent diamonds",
    material: "18K White Gold",
    weight: "5g",
    sku: "RNG-004",
    image: "rings-04.jpg",
    customizable: true,
  },
  {
    id: 5,
    name: "Vintage Filigree Ring",
    category: "Rings",
    price: 1899.99,
    description: "Beautiful vintage-inspired filigree design",
    material: "14K Yellow Gold",
    weight: "3.2g",
    sku: "RNG-005",
    image: "rings-05.jpg",
    customizable: true,
  },
  {
    id: 6,
    name: "Three Stone Diamond Ring",
    category: "Rings",
    price: 5999.99,
    description: "Classic three stone diamond engagement ring",
    material: "Platinum",
    weight: "4.5g",
    sku: "RNG-006",
    image: "rings-06.jpg",
    customizable: true,
  },
  {
    id: 7,
    name: "Eternity Band",
    category: "Rings",
    price: 2499.99,
    description: "Sparkling diamond eternity band",
    material: "18K White Gold",
    weight: "3.8g",
    sku: "RNG-007",
    image: "rings-07.jpg",
    customizable: true,
  },
  {
    id: 8,
    name: "Ruby Anniversary Ring",
    category: "Rings",
    price: 3299.99,
    description: "Gorgeous ruby and diamond anniversary ring",
    material: "14K Gold",
    weight: "4.2g",
    sku: "RNG-008",
    image: "rings-08.jpg",
    customizable: true,
  },
  {
    id: 9,
    name: "Cushion Cut Halo Ring",
    category: "Rings",
    price: 4799.99,
    description: "Stunning cushion cut diamond with halo setting",
    material: "Platinum",
    weight: "4.8g",
    sku: "RNG-009",
    image: "rings-09.jpg",
    customizable: true,
  },
  {
    id: 10,
    name: "Twisted Band Ring",
    category: "Rings",
    price: 1299.99,
    description: "Modern twisted diamond band",
    material: "14K White Gold",
    weight: "3.3g",
    sku: "RNG-010",
    image: "rings-10.jpg",
    customizable: true,
  },
  {
    id: 11,
    name: "Princess Cut Solitaire",
    category: "Rings",
    price: 3899.99,
    description: "Elegant princess cut diamond solitaire",
    material: "18K White Gold",
    weight: "4.1g",
    sku: "RNG-011",
    image: "rings-11.jpg",
    customizable: true,
  },
  {
    id: 12,
    name: "Art Deco Ring",
    category: "Rings",
    price: 2799.99,
    description: "Vintage Art Deco inspired design",
    material: "14K Yellow Gold",
    weight: "3.7g",
    sku: "RNG-012",
    image: "rings-12.jpg",
    customizable: true,
  },
  {
    id: 13,
    name: "Oval Diamond Ring",
    category: "Rings",
    price: 5299.99,
    description: "Beautiful oval diamond with side stones",
    material: "Platinum",
    weight: "5.2g",
    sku: "RNG-013",
    image: "rings-13.jpg",
    customizable: true,
  },
  {
    id: 14,
    name: "Infinity Band",
    category: "Rings",
    price: 1599.99,
    description: "Romantic infinity symbol diamond band",
    material: "14K Rose Gold",
    weight: "3.1g",
    sku: "RNG-014",
    image: "rings-14.jpg",
    customizable: true,
  },
  {
    id: 15,
    name: "Pear Shaped Diamond Ring",
    category: "Rings",
    price: 4599.99,
    description: "Stunning pear shaped diamond ring",
    material: "18K White Gold",
    weight: "4.6g",
    sku: "RNG-015",
    image: "rings-15.jpg",
    customizable: true,
  },
  {
    id: 16,
    name: "Channel Set Band",
    category: "Rings",
    price: 1899.99,
    description: "Modern channel set diamond band",
    material: "14K White Gold",
    weight: "3.4g",
    sku: "RNG-016",
    image: "rings-16.jpg",
    customizable: true,
  },
  {
    id: 17,
    name: "Aquamarine Cocktail Ring",
    category: "Rings",
    price: 2299.99,
    description: "Bold aquamarine statement ring",
    material: "14K Gold",
    weight: "5.5g",
    sku: "RNG-017",
    image: "rings-17.jpg",
    customizable: true,
  },
  {
    id: 18,
    name: "Bypass Diamond Ring",
    category: "Rings",
    price: 2699.99,
    description: "Contemporary bypass style diamond ring",
    material: "18K White Gold",
    weight: "3.9g",
    sku: "RNG-018",
    image: "rings-18.jpg",
    customizable: true,
  },
  {
    id: 19,
    name: "Stacking Ring Set",
    category: "Rings",
    price: 1199.99,
    description: "Delicate stackable diamond rings",
    material: "14K Yellow Gold",
    weight: "2.8g",
    sku: "RNG-019",
    image: "rings-19.jpg",
    customizable: true,
  },
  {
    id: 20,
    name: "Tension Set Ring",
    category: "Rings",
    price: 3599.99,
    description: "Modern tension set diamond ring",
    material: "Platinum",
    weight: "4.3g",
    sku: "RNG-020",
    image: "rings-20.jpg",
    customizable: true,
  },
  {
    id: 21,
    name: "Bezel Set Diamond Ring",
    category: "Rings",
    price: 2199.99,
    description: "Sleek bezel set diamond design",
    material: "14K White Gold",
    weight: "3.6g",
    sku: "RNG-021",
    image: "rings-21.jpg",
    customizable: false,
  },
  {
    id: 22,
    name: "Milgrain Detail Ring",
    category: "Rings",
    price: 1799.99,
    description: "Vintage milgrain detail diamond ring",
    material: "14K Yellow Gold",
    weight: "3.3g",
    sku: "RNG-022",
    image: "rings-22.jpg",
    customizable: false,
  },
  {
    id: 23,
    name: "Split Shank Ring",
    category: "Rings",
    price: 4199.99,
    description: "Elegant split shank diamond ring",
    material: "18K White Gold",
    weight: "4.7g",
    sku: "RNG-023",
    image: "rings-23.jpg",
    customizable: false,
  },
  {
    id: 24,
    name: "Crossover Diamond Ring",
    category: "Rings",
    price: 2899.99,
    description: "Modern crossover style ring",
    material: "14K Rose Gold",
    weight: "3.8g",
    sku: "RNG-024",
    image: "rings-24.jpg",
    customizable: false,
  },
  {
    id: 25,
    name: "Cathedral Setting Ring",
    category: "Rings",
    price: 3799.99,
    description: "Classic cathedral setting engagement ring",
    material: "Platinum",
    weight: "4.4g",
    sku: "RNG-025",
    image: "rings-25.jpg",
    customizable: false,
  },
  {
    id: 26,
    name: "Pave Diamond Band",
    category: "Rings",
    price: 2399.99,
    description: "Sparkling pave diamond band",
    material: "18K White Gold",
    weight: "3.5g",
    sku: "RNG-026",
    image: "rings-26.jpg",
    customizable: false,
  },
  {
    id: 27,
    name: "Marquise Diamond Ring",
    category: "Rings",
    price: 4899.99,
    description: "Elegant marquise cut diamond ring",
    material: "Platinum",
    weight: "4.9g",
    sku: "RNG-027",
    image: "rings-27.jpg",
    customizable: false,
  },
  {
    id: 28,
    name: "Cluster Diamond Ring",
    category: "Rings",
    price: 2599.99,
    description: "Beautiful diamond cluster design",
    material: "14K Gold",
    weight: "4.1g",
    sku: "RNG-028",
    image: "rings-28.jpg",
    customizable: false,
  },
  {
    id: 29,
    name: "Geometric Modern Ring",
    category: "Rings",
    price: 1999.99,
    description: "Contemporary geometric diamond ring",
    material: "14K White Gold",
    weight: "3.2g",
    sku: "RNG-029",
    image: "rings-29.jpg",
    customizable: false,
  },
  {
    id: 30,
    name: "Heirloom Style Ring",
    category: "Rings",
    price: 3299.99,
    description: "Timeless heirloom style ring",
    material: "18K Yellow Gold",
    weight: "4.3g",
    sku: "RNG-030",
    image: "rings-30.jpg",
    customizable: false,
  },
  {
    id: 31,
    name: "Heart Diamond Ring",
    category: "Rings",
    price: 2799.99,
    description: "Romantic heart shaped diamond ring",
    material: "14K Rose Gold",
    weight: "3.7g",
    sku: "RNG-031",
    image: "rings-31.jpg",
    customizable: false,
  },
  {
    id: 32,
    name: "Open Shank Ring",
    category: "Rings",
    price: 2199.99,
    description: "Modern open shank diamond ring",
    material: "14K White Gold",
    weight: "3.4g",
    sku: "RNG-032",
    image: "rings-32.jpg",
    customizable: false,
  },
  {
    id: 33,
    name: "Vintage Inspired Ring",
    category: "Rings",
    price: 2999.99,
    description: "Beautiful vintage inspired design",
    material: "18K Gold",
    weight: "4.2g",
    sku: "RNG-033",
    image: "rings-33.jpg",
    customizable: false,
  },
  {
    id: 34,
    name: "Contemporary Diamond Ring",
    category: "Rings",
    price: 3499.99,
    description: "Sleek contemporary diamond ring",
    material: "Platinum",
    weight: "4.5g",
    sku: "RNG-034",
    image: "rings-34.jpg",
    customizable: false,
  },

  // Necklaces (46 items)
  {
    id: 35,
    name: "Pearl Strand Necklace",
    category: "Necklaces",
    price: 899.99,
    description: "Classic freshwater pearl strand",
    material: "Sterling Silver",
    weight: "12g",
    sku: "NCK-001",
    image: "necklaces-01.jpg",
    customizable: false,
  },
  {
    id: 36,
    name: "Diamond Pendant",
    category: "Necklaces",
    price: 1999.99,
    description: "Elegant diamond solitaire pendant",
    material: "14K White Gold",
    weight: "8g",
    sku: "NCK-002",
    image: "necklaces-02.jpg",
    customizable: false,
  },
  {
    id: 37,
    name: "Gold Chain Necklace",
    category: "Necklaces",
    price: 699.99,
    description: "Luxurious gold link chain",
    material: "18K Gold",
    weight: "15g",
    sku: "NCK-003",
    image: "necklaces-03.jpg",
    customizable: false,
  },
  {
    id: 38,
    name: "Gemstone Bar Necklace",
    category: "Necklaces",
    price: 599.99,
    description: "Modern bar necklace with gemstones",
    material: "14K Rose Gold",
    weight: "6g",
    sku: "NCK-004",
    image: "necklaces-04.jpg",
    customizable: false,
  },
  {
    id: 39,
    name: "Lariat Style Necklace",
    category: "Necklaces",
    price: 1299.99,
    description: "Elegant lariat style design",
    material: "14K Gold",
    weight: "10g",
    sku: "NCK-005",
    image: "necklaces-05.jpg",
    customizable: false,
  },
  {
    id: 40,
    name: "Heart Pendant Necklace",
    category: "Necklaces",
    price: 799.99,
    description: "Romantic heart shaped pendant",
    material: "Sterling Silver",
    weight: "7g",
    sku: "NCK-006",
    image: "necklaces-06.jpg",
    customizable: false,
  },
  {
    id: 41,
    name: "Choker Necklace",
    category: "Necklaces",
    price: 1499.99,
    description: "Stylish diamond choker",
    material: "18K White Gold",
    weight: "14g",
    sku: "NCK-007",
    image: "necklaces-07.jpg",
    customizable: false,
  },
  {
    id: 42,
    name: "Layered Chain Necklace",
    category: "Necklaces",
    price: 899.99,
    description: "Trendy layered chain design",
    material: "14K Gold",
    weight: "11g",
    sku: "NCK-008",
    image: "necklaces-08.jpg",
    customizable: false,
  },
  {
    id: 43,
    name: "Cross Pendant",
    category: "Necklaces",
    price: 1199.99,
    description: "Beautiful diamond cross pendant",
    material: "14K White Gold",
    weight: "9g",
    sku: "NCK-009",
    image: "necklaces-09.jpg",
    customizable: false,
  },
  {
    id: 44,
    name: "Infinity Necklace",
    category: "Necklaces",
    price: 699.99,
    description: "Delicate infinity symbol necklace",
    material: "Sterling Silver",
    weight: "5g",
    sku: "NCK-010",
    image: "necklaces-10.jpg",
    customizable: false,
  },
  {
    id: 45,
    name: "Station Necklace",
    category: "Necklaces",
    price: 1599.99,
    description: "Elegant diamond station necklace",
    material: "18K Gold",
    weight: "13g",
    sku: "NCK-011",
    image: "necklaces-11.jpg",
    customizable: false,
  },
  {
    id: 46,
    name: "Cameo Pendant",
    category: "Necklaces",
    price: 999.99,
    description: "Vintage style cameo pendant",
    material: "14K Yellow Gold",
    weight: "10g",
    sku: "NCK-012",
    image: "necklaces-12.jpg",
    customizable: false,
  },
  {
    id: 47,
    name: "Tassel Necklace",
    category: "Necklaces",
    price: 1199.99,
    description: "Modern tassel design necklace",
    material: "14K Rose Gold",
    weight: "12g",
    sku: "NCK-013",
    image: "necklaces-13.jpg",
    customizable: false,
  },
  {
    id: 48,
    name: "Evil Eye Necklace",
    category: "Necklaces",
    price: 599.99,
    description: "Protective evil eye pendant",
    material: "Sterling Silver",
    weight: "6g",
    sku: "NCK-014",
    image: "necklaces-14.jpg",
    customizable: false,
  },
  {
    id: 49,
    name: "Birthstone Necklace",
    category: "Necklaces",
    price: 799.99,
    description: "Personalized birthstone pendant",
    material: "14K Gold",
    weight: "7g",
    sku: "NCK-015",
    image: "necklaces-15.jpg",
    customizable: false,
  },
  {
    id: 50,
    name: "Vintage Locket",
    category: "Necklaces",
    price: 899.99,
    description: "Antique style photo locket",
    material: "14K Yellow Gold",
    weight: "11g",
    sku: "NCK-016",
    image: "necklaces-16.jpg",
    customizable: false,
  },
  {
    id: 51,
    name: "Initial Pendant",
    category: "Necklaces",
    price: 499.99,
    description: "Personalized initial pendant",
    material: "Sterling Silver",
    weight: "5g",
    sku: "NCK-017",
    image: "necklaces-17.jpg",
    customizable: false,
  },
  {
    id: 52,
    name: "Hamsa Hand Necklace",
    category: "Necklaces",
    price: 699.99,
    description: "Symbolic hamsa hand pendant",
    material: "14K Gold",
    weight: "8g",
    sku: "NCK-018",
    image: "necklaces-18.jpg",
    customizable: false,
  },
  {
    id: 53,
    name: "Geometric Pendant",
    category: "Necklaces",
    price: 999.99,
    description: "Modern geometric design pendant",
    material: "18K White Gold",
    weight: "9g",
    sku: "NCK-019",
    image: "necklaces-19.jpg",
    customizable: false,
  },
  {
    id: 54,
    name: "Moonstone Necklace",
    category: "Necklaces",
    price: 799.99,
    description: "Mystical moonstone pendant",
    material: "Sterling Silver",
    weight: "7g",
    sku: "NCK-020",
    image: "necklaces-20.jpg",
    customizable: false,
  },
  {
    id: 55,
    name: "Y-Shape Necklace",
    category: "Necklaces",
    price: 1299.99,
    description: "Elegant Y-shape diamond necklace",
    material: "14K White Gold",
    weight: "10g",
    sku: "NCK-021",
    image: "necklaces-21.jpg",
    customizable: false,
  },
  {
    id: 56,
    name: "Coin Pendant Necklace",
    category: "Necklaces",
    price: 899.99,
    description: "Trendy coin pendant design",
    material: "14K Gold",
    weight: "9g",
    sku: "NCK-022",
    image: "necklaces-22.jpg",
    customizable: false,
  },
  {
    id: 57,
    name: "Feather Pendant",
    category: "Necklaces",
    price: 699.99,
    description: "Delicate feather design pendant",
    material: "Sterling Silver",
    weight: "6g",
    sku: "NCK-023",
    image: "necklaces-23.jpg",
    customizable: false,
  },
  {
    id: 58,
    name: "Halo Pendant Necklace",
    category: "Necklaces",
    price: 1599.99,
    description: "Sparkling halo diamond pendant",
    material: "18K White Gold",
    weight: "11g",
    sku: "NCK-024",
    image: "necklaces-24.jpg",
    customizable: false,
  },
  {
    id: 59,
    name: "Charm Necklace",
    category: "Necklaces",
    price: 999.99,
    description: "Customizable charm necklace",
    material: "14K Rose Gold",
    weight: "10g",
    sku: "NCK-025",
    image: "necklaces-25.jpg",
    customizable: false,
  },
  {
    id: 60,
    name: "Emerald Pendant",
    category: "Necklaces",
    price: 1799.99,
    description: "Stunning emerald drop pendant",
    material: "14K Gold",
    weight: "12g",
    sku: "NCK-026",
    image: "necklaces-26.jpg",
    customizable: false,
  },
  {
    id: 61,
    name: "Art Deco Necklace",
    category: "Necklaces",
    price: 1999.99,
    description: "Vintage Art Deco style necklace",
    material: "Platinum",
    weight: "15g",
    sku: "NCK-027",
    image: "necklaces-27.jpg",
    customizable: false,
  },
  {
    id: 62,
    name: "Sapphire Pendant",
    category: "Necklaces",
    price: 1699.99,
    description: "Beautiful sapphire pendant necklace",
    material: "14K White Gold",
    weight: "10g",
    sku: "NCK-028",
    image: "necklaces-28.jpg",
    customizable: false,
  },
  {
    id: 63,
    name: "Rope Chain Necklace",
    category: "Necklaces",
    price: 799.99,
    description: "Classic rope chain design",
    material: "14K Gold",
    weight: "13g",
    sku: "NCK-029",
    image: "necklaces-29.jpg",
    customizable: false,
  },
  {
    id: 64,
    name: "Star Pendant Necklace",
    category: "Necklaces",
    price: 699.99,
    description: "Celestial star pendant",
    material: "Sterling Silver",
    weight: "6g",
    sku: "NCK-030",
    image: "necklaces-30.jpg",
    customizable: false,
  },
  {
    id: 65,
    name: "Teardrop Pendant",
    category: "Necklaces",
    price: 1299.99,
    description: "Elegant teardrop gemstone pendant",
    material: "18K White Gold",
    weight: "11g",
    sku: "NCK-031",
    image: "necklaces-31.jpg",
    customizable: false,
  },
  {
    id: 66,
    name: "Snake Chain Necklace",
    category: "Necklaces",
    price: 599.99,
    description: "Sleek snake chain design",
    material: "Sterling Silver",
    weight: "8g",
    sku: "NCK-032",
    image: "necklaces-32.jpg",
    customizable: false,
  },
  {
    id: 67,
    name: "Floral Pendant",
    category: "Necklaces",
    price: 999.99,
    description: "Delicate floral design pendant",
    material: "14K Rose Gold",
    weight: "9g",
    sku: "NCK-033",
    image: "necklaces-33.jpg",
    customizable: false,
  },
  {
    id: 68,
    name: "Byzantine Chain",
    category: "Necklaces",
    price: 1499.99,
    description: "Intricate Byzantine chain necklace",
    material: "14K Gold",
    weight: "16g",
    sku: "NCK-034",
    image: "necklaces-34.jpg",
    customizable: false,
  },
  {
    id: 69,
    name: "Tree of Life Pendant",
    category: "Necklaces",
    price: 799.99,
    description: "Symbolic tree of life design",
    material: "Sterling Silver",
    weight: "7g",
    sku: "NCK-035",
    image: "necklaces-35.jpg",
    customizable: false,
  },
  {
    id: 70,
    name: "Oval Pendant Necklace",
    category: "Necklaces",
    price: 1199.99,
    description: "Classic oval gemstone pendant",
    material: "14K White Gold",
    weight: "10g",
    sku: "NCK-036",
    image: "necklaces-36.jpg",
    customizable: false,
  },
  {
    id: 71,
    name: "Multi-Strand Necklace",
    category: "Necklaces",
    price: 1599.99,
    description: "Elegant multi-strand design",
    material: "18K Gold",
    weight: "14g",
    sku: "NCK-037",
    image: "necklaces-37.jpg",
    customizable: false,
  },
  {
    id: 72,
    name: "Anchor Pendant",
    category: "Necklaces",
    price: 699.99,
    description: "Nautical anchor pendant",
    material: "Sterling Silver",
    weight: "8g",
    sku: "NCK-038",
    image: "necklaces-38.jpg",
    customizable: false,
  },
  {
    id: 73,
    name: "Butterfly Pendant",
    category: "Necklaces",
    price: 899.99,
    description: "Delicate butterfly design",
    material: "14K Rose Gold",
    weight: "7g",
    sku: "NCK-039",
    image: "necklaces-39.jpg",
    customizable: false,
  },
  {
    id: 74,
    name: "Tennis Necklace",
    category: "Necklaces",
    price: 2499.99,
    description: "Classic diamond tennis necklace",
    material: "18K White Gold",
    weight: "17g",
    sku: "NCK-040",
    image: "necklaces-40.jpg",
    customizable: false,
  },
  {
    id: 75,
    name: "Clover Pendant",
    category: "Necklaces",
    price: 999.99,
    description: "Lucky four-leaf clover pendant",
    material: "14K Gold",
    weight: "8g",
    sku: "NCK-041",
    image: "necklaces-41.jpg",
    customizable: false,
  },
  {
    id: 76,
    name: "Key Pendant Necklace",
    category: "Necklaces",
    price: 799.99,
    description: "Vintage key design pendant",
    material: "Sterling Silver",
    weight: "9g",
    sku: "NCK-042",
    image: "necklaces-42.jpg",
    customizable: false,
  },
  {
    id: 77,
    name: "Crown Pendant",
    category: "Necklaces",
    price: 1199.99,
    description: "Royal crown design pendant",
    material: "14K Gold",
    weight: "10g",
    sku: "NCK-043",
    image: "necklaces-43.jpg",
    customizable: false,
  },
  {
    id: 80,
    name: "Wave Pendant Necklace",
    category: "Necklaces",
    price: 899.99,
    description: "Ocean wave inspired design",
    material: "Sterling Silver",
    weight: "8g",
    sku: "NCK-046",
    image: "necklaces-46.jpg",
    customizable: false,
  },

  // Bracelets (19 items)
  {
    id: 81,
    name: "Tennis Bracelet",
    category: "Bracelets",
    price: 1999.99,
    description: "Classic diamond tennis bracelet",
    material: "14K White Gold",
    weight: "12g",
    sku: "BRC-001",
    image: "bracelets-01.jpg",
    customizable: false,
  },
  {
    id: 82,
    name: "Gold Bangle",
    category: "Bracelets",
    price: 899.99,
    description: "Elegant solid gold bangle",
    material: "18K Gold",
    weight: "15g",
    sku: "BRC-002",
    image: "bracelets-02.jpg",
    customizable: false,
  },
  {
    id: 83,
    name: "Charm Bracelet",
    category: "Bracelets",
    price: 699.99,
    description: "Personalized charm bracelet",
    material: "Sterling Silver",
    weight: "10g",
    sku: "BRC-003",
    image: "bracelets-03.jpg",
    customizable: false,
  },
  {
    id: 84,
    name: "Cuff Bracelet",
    category: "Bracelets",
    price: 1299.99,
    description: "Bold statement cuff bracelet",
    material: "14K Gold",
    weight: "18g",
    sku: "BRC-004",
    image: "bracelets-04.jpg",
    customizable: false,
  },
  {
    id: 85,
    name: "Chain Link Bracelet",
    category: "Bracelets",
    price: 799.99,
    description: "Modern chain link design",
    material: "14K Rose Gold",
    weight: "11g",
    sku: "BRC-005",
    image: "bracelets-05.jpg",
    customizable: false,
  },
  {
    id: 86,
    name: "Beaded Bracelet",
    category: "Bracelets",
    price: 499.99,
    description: "Delicate beaded design",
    material: "Sterling Silver",
    weight: "8g",
    sku: "BRC-006",
    image: "bracelets-06.jpg",
    customizable: false,
  },
  {
    id: 87,
    name: "Bolo Bracelet",
    category: "Bracelets",
    price: 999.99,
    description: "Adjustable bolo style bracelet",
    material: "14K White Gold",
    weight: "9g",
    sku: "BRC-007",
    image: "bracelets-07.jpg",
    customizable: false,
  },
  {
    id: 89,
    name: "Wrap Bracelet",
    category: "Bracelets",
    price: 599.99,
    description: "Trendy leather wrap bracelet",
    material: "Sterling Silver",
    weight: "7g",
    sku: "BRC-009",
    image: "bracelets-09.jpg",
    customizable: false,
  },
  {
    id: 90,
    name: "ID Bracelet",
    category: "Bracelets",
    price: 699.99,
    description: "Personalized ID bracelet",
    material: "14K Gold",
    weight: "12g",
    sku: "BRC-010",
    image: "bracelets-10.jpg",
    customizable: false,
  },
  {
    id: 91,
    name: "Curb Chain Bracelet",
    category: "Bracelets",
    price: 899.99,
    description: "Classic curb chain design",
    material: "14K Gold",
    weight: "14g",
    sku: "BRC-011",
    image: "bracelets-11.jpg",
    customizable: false,
  },
  {
    id: 92,
    name: "Gemstone Bracelet",
    category: "Bracelets",
    price: 1199.99,
    description: "Colorful gemstone tennis bracelet",
    material: "14K White Gold",
    weight: "11g",
    sku: "BRC-012",
    image: "bracelets-12.jpg",
    customizable: false,
  },
  {
    id: 93,
    name: "Pearl Bracelet",
    category: "Bracelets",
    price: 799.99,
    description: "Elegant freshwater pearl bracelet",
    material: "Sterling Silver",
    weight: "9g",
    sku: "BRC-013",
    image: "bracelets-13.jpg",
    customizable: false,
  },
  {
    id: 94,
    name: "Slider Bracelet",
    category: "Bracelets",
    price: 999.99,
    description: "Adjustable slider design",
    material: "14K Rose Gold",
    weight: "10g",
    sku: "BRC-014",
    image: "bracelets-14.jpg",
    customizable: false,
  },
  {
    id: 95,
    name: "Rope Bracelet",
    category: "Bracelets",
    price: 699.99,
    description: "Twisted rope design bracelet",
    material: "14K Gold",
    weight: "13g",
    sku: "BRC-015",
    image: "bracelets-15.jpg",
    customizable: false,
  },
  {
    id: 96,
    name: "Byzantine Bracelet",
    category: "Bracelets",
    price: 1299.99,
    description: "Intricate Byzantine chain",
    material: "18K Gold",
    weight: "17g",
    sku: "BRC-016",
    image: "bracelets-16.jpg",
    customizable: false,
  },

  // Earrings (4 items)
  {
    id: 100,
    name: "Diamond Studs",
    category: "Earrings",
    price: 1499.99,
    description: "Classic diamond stud earrings",
    material: "14K White Gold",
    weight: "2g",
    sku: "ERG-001",
    image: "earrings-01.jpg",
    customizable: false,
  },
  {
    id: 101,
    name: "Hoop Earrings",
    category: "Earrings",
    price: 799.99,
    description: "Elegant gold hoop earrings",
    material: "14K Gold",
    weight: "3g",
    sku: "ERG-002",
    image: "earrings-02.jpg",
    customizable: false,
  },
  {
    id: 102,
    name: "Drop Earrings",
    category: "Earrings",
    price: 1299.99,
    description: "Beautiful gemstone drop earrings",
    material: "14K Rose Gold",
    weight: "4g",
    sku: "ERG-003",
    image: "earrings-03.jpg",
    customizable: false,
  },
  {
    id: 103,
    name: "Huggie Earrings",
    category: "Earrings",
    price: 699.99,
    description: "Modern diamond huggie earrings",
    material: "14K White Gold",
    weight: "2.5g",
    sku: "ERG-004",
    image: "earrings-04.jpg",
    customizable: false,
  },

  // Watches (114 items - showing first 30 for brevity)
  {
    id: 104,
    name: "Luxury Diamond Watch",
    category: "Watches",
    price: 8999.99,
    description: "Premium watch with diamond bezel",
    material: "Stainless Steel",
    weight: "150g",
    sku: "WCH-001",
    image: "watches-01.jpg",
    customizable: false,
  },
  {
    id: 105,
    name: "Rose Gold Watch",
    category: "Watches",
    price: 5999.99,
    description: "Elegant rose gold timepiece",
    material: "Rose Gold",
    weight: "120g",
    sku: "WCH-002",
    image: "watches-02.jpg",
    customizable: false,
  },
  {
    id: 106,
    name: "Chronograph Watch",
    category: "Watches",
    price: 4999.99,
    description: "Professional chronograph watch",
    material: "Stainless Steel",
    weight: "140g",
    sku: "WCH-003",
    image: "watches-03.jpg",
    customizable: false,
  },
  {
    id: 107,
    name: "Classic Dress Watch",
    category: "Watches",
    price: 3999.99,
    description: "Timeless dress watch design",
    material: "Leather Band",
    weight: "80g",
    sku: "WCH-004",
    image: "watches-04.jpg",
    customizable: false,
  },
  {
    id: 108,
    name: "Sport Watch",
    category: "Watches",
    price: 2999.99,
    description: "Durable sport watch",
    material: "Titanium",
    weight: "100g",
    sku: "WCH-005",
    image: "watches-05.jpg",
    customizable: false,
  },
  {
    id: 109,
    name: "Automatic Watch",
    category: "Watches",
    price: 6999.99,
    description: "Sophisticated automatic movement",
    material: "Stainless Steel",
    weight: "145g",
    sku: "WCH-006",
    image: "watches-06.jpg",
    customizable: false,
  },
  {
    id: 110,
    name: "Dive Watch",
    category: "Watches",
    price: 4499.99,
    description: "Professional dive watch",
    material: "Stainless Steel",
    weight: "160g",
    sku: "WCH-007",
    image: "watches-07.jpg",
    customizable: false,
  },
  {
    id: 111,
    name: "Smart Watch",
    category: "Watches",
    price: 3499.99,
    description: "Modern smart watch",
    material: "Aluminum",
    weight: "50g",
    sku: "WCH-008",
    image: "watches-08.jpg",
    customizable: false,
  },
  {
    id: 112,
    name: "Skeleton Watch",
    category: "Watches",
    price: 7999.99,
    description: "Stunning skeleton dial watch",
    material: "Stainless Steel",
    weight: "135g",
    sku: "WCH-009",
    image: "watches-09.jpg",
    customizable: false,
  },
  {
    id: 113,
    name: "Vintage Watch",
    category: "Watches",
    price: 5499.99,
    description: "Classic vintage style watch",
    material: "Gold Plated",
    weight: "110g",
    sku: "WCH-010",
    image: "watches-10.jpg",
    customizable: false,
  },
  {
    id: 114,
    name: "Moon Phase Watch",
    category: "Watches",
    price: 8499.99,
    description: "Elegant moon phase complication",
    material: "Stainless Steel",
    weight: "155g",
    sku: "WCH-011",
    image: "watches-11.jpg",
    customizable: false,
  },
  {
    id: 115,
    name: "GMT Watch",
    category: "Watches",
    price: 5999.99,
    description: "Dual time zone GMT watch",
    material: "Stainless Steel",
    weight: "148g",
    sku: "WCH-012",
    image: "watches-12.jpg",
    customizable: false,
  },
  {
    id: 116,
    name: "Pilot Watch",
    category: "Watches",
    price: 4999.99,
    description: "Aviation inspired pilot watch",
    material: "Stainless Steel",
    weight: "142g",
    sku: "WCH-013",
    image: "watches-13.jpg",
    customizable: false,
  },
  {
    id: 117,
    name: "Racing Watch",
    category: "Watches",
    price: 6499.99,
    description: "Motorsport chronograph watch",
    material: "Titanium",
    weight: "130g",
    sku: "WCH-014",
    image: "watches-14.jpg",
    customizable: false,
  },
  {
    id: 118,
    name: "Minimalist Watch",
    category: "Watches",
    price: 2499.99,
    description: "Clean minimalist design",
    material: "Stainless Steel",
    weight: "75g",
    sku: "WCH-015",
    image: "watches-15.jpg",
    customizable: false,
  },
  {
    id: 119,
    name: "Field Watch",
    category: "Watches",
    price: 3499.99,
    description: "Rugged field watch",
    material: "Stainless Steel",
    weight: "115g",
    sku: "WCH-016",
    image: "watches-16.jpg",
    customizable: false,
  },
  {
    id: 120,
    name: "Tourbillon Watch",
    category: "Watches",
    price: 15999.99,
    description: "Prestigious tourbillon movement",
    material: "18K Gold",
    weight: "165g",
    sku: "WCH-017",
    image: "watches-17.jpg",
    customizable: false,
  },
  {
    id: 121,
    name: "Perpetual Calendar",
    category: "Watches",
    price: 12999.99,
    description: "Complex perpetual calendar",
    material: "Platinum",
    weight: "170g",
    sku: "WCH-018",
    image: "watches-18.jpg",
    customizable: false,
  },
  {
    id: 122,
    name: "Regulator Watch",
    category: "Watches",
    price: 7499.99,
    description: "Unique regulator dial layout",
    material: "Stainless Steel",
    weight: "138g",
    sku: "WCH-019",
    image: "watches-19.jpg",
    customizable: false,
  },
  {
    id: 123,
    name: "Worldtimer Watch",
    category: "Watches",
    price: 9999.99,
    description: "Global worldtime function",
    material: "Stainless Steel",
    weight: "158g",
    sku: "WCH-020",
    image: "watches-20.jpg",
    customizable: false,
  },
  {
    id: 124,
    name: "Power Reserve Watch",
    category: "Watches",
    price: 6999.99,
    description: "Visible power reserve indicator",
    material: "Stainless Steel",
    weight: "145g",
    sku: "WCH-021",
    image: "watches-21.jpg",
    customizable: false,
  },
  {
    id: 125,
    name: "Retrograde Watch",
    category: "Watches",
    price: 5499.99,
    description: "Unique retrograde complication",
    material: "Stainless Steel",
    weight: "140g",
    sku: "WCH-022",
    image: "watches-22.jpg",
    customizable: false,
  },
  {
    id: 126,
    name: "Dual Display Watch",
    category: "Watches",
    price: 3999.99,
    description: "Analog and digital display",
    material: "Titanium",
    weight: "95g",
    sku: "WCH-023",
    image: "watches-23.jpg",
    customizable: false,
  },
  {
    id: 127,
    name: "Bronze Watch",
    category: "Watches",
    price: 4499.99,
    description: "Distinctive bronze case watch",
    material: "Bronze",
    weight: "125g",
    sku: "WCH-024",
    image: "watches-24.jpg",
    customizable: false,
  },
  {
    id: 128,
    name: "Ceramic Watch",
    category: "Watches",
    price: 5999.99,
    description: "Scratch-resistant ceramic",
    material: "Ceramic",
    weight: "88g",
    sku: "WCH-025",
    image: "watches-25.jpg",
    customizable: false,
  },
  {
    id: 129,
    name: "Carbon Fiber Watch",
    category: "Watches",
    price: 7999.99,
    description: "Lightweight carbon fiber case",
    material: "Carbon Fiber",
    weight: "65g",
    sku: "WCH-026",
    image: "watches-26.jpg",
    customizable: false,
  },
  {
    id: 130,
    name: "Two-Tone Watch",
    category: "Watches",
    price: 4999.99,
    description: "Classic two-tone design",
    material: "Steel & Gold",
    weight: "135g",
    sku: "WCH-027",
    image: "watches-27.jpg",
    customizable: false,
  },
  {
    id: 131,
    name: "Rectangular Watch",
    category: "Watches",
    price: 3999.99,
    description: "Elegant rectangular case",
    material: "Stainless Steel",
    weight: "105g",
    sku: "WCH-028",
    image: "watches-28.jpg",
    customizable: false,
  },
  {
    id: 132,
    name: "Cushion Case Watch",
    category: "Watches",
    price: 5499.99,
    description: "Vintage cushion case design",
    material: "Stainless Steel",
    weight: "128g",
    sku: "WCH-029",
    image: "watches-29.jpg",
    customizable: false,
  },
  {
    id: 133,
    name: "Tonneau Watch",
    category: "Watches",
    price: 6499.99,
    description: "Distinctive tonneau shape",
    material: "Rose Gold",
    weight: "115g",
    sku: "WCH-030",
    image: "watches-30.jpg",
    customizable: false,
  },

  // Custom Featured Products (6 items)
  {
    id: 500,
    name: "Custom Engraved Pendant",
    category: "Custom",
    price: 15000,
    description: "Personalized pendant with custom engraving",
    material: "Sterling Silver",
    weight: "8g",
    sku: "CUS-001",
    image: "custom-01.jpg",
    customizable: true,
  },
  {
    id: 501,
    name: "Bespoke Wedding Ring",
    category: "Custom",
    price: 45000,
    description: "Custom designed wedding ring",
    material: "18K Gold",
    weight: "6g",
    sku: "CUS-002",
    image: "custom-02.jpg",
    customizable: true,
  },
  {
    id: 502,
    name: "Personalized Bracelet",
    category: "Custom",
    price: 20000,
    description: "Charm bracelet with custom charms",
    material: "14K Gold",
    weight: "12g",
    sku: "CUS-003",
    image: "custom-03.jpg",
    customizable: true,
  },
  {
    id: 503,
    name: "Custom Name Necklace",
    category: "Custom",
    price: 18000,
    description: "Necklace with your name in elegant script",
    material: "14K Rose Gold",
    weight: "10g",
    sku: "CUS-004",
    image: "custom-04.jpg",
    customizable: true,
  },
  {
    id: 504,
    name: "Engraved Cufflinks",
    category: "Custom",
    price: 12000,
    description: "Personalized cufflinks with initials",
    material: "Sterling Silver",
    weight: "15g",
    sku: "CUS-005",
    image: "custom-05.jpg",
    customizable: true,
  },
  {
    id: 505,
    name: "Custom Photo Locket",
    category: "Custom",
    price: 25000,
    description: "Locket with your photo engraved",
    material: "14K Gold",
    weight: "11g",
    sku: "CUS-006",
    image: "custom-06.jpg",
    customizable: true,
  },
];

function App() {
  const dispatch = useDispatch();

  useEffect(() => {
    // Load sample products into Redux store
    dispatch(setProducts(sampleProducts));
  }, [dispatch]);

  return (
    <Router>
      <ScrollToTop />
      <div className="App">
        <Navbar />
        <main className="main-content">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/products" element={<Products />} />
            <Route path="/products/:id" element={<ProductDetail />} />
            <Route path="/customization" element={<Customization />}>
              <Route path="create" element={<CreateCustomization />} />
            </Route>
            <Route path="/cart" element={<Cart />} />
            <Route path="/checkout" element={<Checkout />} />
            <Route path="/login" element={<Login />} />
            <Route path="/track-order" element={<TrackOrder />} />
            <Route path="/contact" element={<ContactUs />} />
            <Route path="/profile" element={<Profile />} />
            <Route path="*" element={<NotFound />} />
          </Routes>
        </main>
        <Footer />
      </div>
    </Router>
  );
}

export default App;
